comment ::= ? #.*$ ?
identifier ::= ? {XID_Start}{XID_Continue}* ?
number ::= ? [0-9]+ ? | ? 0x[0-9A-Fa-f]+ ?
channel ::= ? 1 | ... | 16 ?

command ::=
	'go' |
	'stop' |
	'left' <integer> |
	'right' <integer> |
	'velocity' <integer> |
	'bpm' <integer> |
	'time' <integer>

action ::= <identifier> <command>+ [ ',' <action> ]

let ::= 'let' ( <identifier> <integer> )+
instrument ::= 'instr' ( <identifier> <string> <channel> )+
control ::= 'ctrl' ( <identifier> <integer> )+

expr ::= ( <let> | <instruction> | <control> | <action> ) '\n'

