comment ::= ? #.*$ ?
identifier ::= ? {XID_Start}{XID_Continue}* ?
number ::= ? [0-9]+ ? | ? 0x[0-9A-Fa-f]+ ?

string_or_identifier ::= <string> | <identifier>
number_or_identifier ::= <number> | <identifier>
midi_or_identifier ::= <midi> | <identifier>

midi ::= <string_or_identifier> ':' <number_or_identifier>

command ::=
	'go' |
	'stop' |
	'clear' |
	'left' <number> |
	'right' <number> |
	'velocity' <number> |
	'bpm' <number> |
	'time' <number>

top_level_command ::=
	'go' |
	'stop' |
	'clear'

action ::= <midi_or_identifier> <command>+

let ::= 'let' ( <identifier> ( <literal> | <midi> ) )+
instrument ::= 'instr' ( <identifier> <midi> )+
control ::= 'ctrl' ( <identifier> <number_or_identifier> )+

expr ::= <let> | <instruction> | <control> | <action> | <top_level_command>
program ::= <expr> [ ',' <expr> ]* '\n'

